spring:
  datasource:
    schema: classpath:import.sql
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console

facebook:
  client:
    clientId: 1861225734138705
    clientSecret: ce8b494d284795dcfc806a5cb05492b3
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.security: INFO
    com.guppy.repository: TRACE